# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: false
sudo: required

matrix:
  include:
    - r: release
      os: linux
      dist: xenial
      after_success:
        - Rscript -e 'covr::codecov()'
        - find . -name *.Rout | xargs cat
    - r: devel
      os: linux
      dist: xenial
    - r: oldrel
      os: linux
      dist: xenial


repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - testthat
  - reticulate

before_script:
  - R -e "reticulate::install_miniconda()"
  - R -e "reticulate::conda_install(envname = 'r-reticulate', 'tensorflow==2.0.0', pip = FALSE)"

after_success:
  - find . -name *.Rout | xargs cat

after_failure:
  - find . -name *.Rout | xargs cat
