# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
sudo: required
language: R
latex: true
cache: packages

addons:
  apt:
    update: true
    packages:
      - python3
      - python-virtualenv

r:
 - devel
 - release
 - oldrel

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - reticulate
  - tinytest

env:
  - TT_AT_CI=TRUE

warnings_are_errors: true

before_script:
  - R -e "reticulate::install_miniconda()"
  - R -e "reticulate::conda_install(envname = 'r-reticulate', 'tensorflow==2.0.0')"

script:
  - R CMD INSTALL ../deepredeff
  - R CMD build .
  - R CMD check --as-cran --no-manual --no-tests --run-donttest *tar.gz
  - R CMD check --as-cran --no-manual *tar.gz

after_success:
  - find . -name *.Rout | xargs cat

after_failure:
  - find . -name *.Rout | xargs cat
